### ISSUE TITLE
HTML to JSX converter doesn't correctly parse className parameter in tag

### ISSUE THREAD

**Issue by Daniel15** [reactjs/react-magic#7] opened 2014-09-21 09:56 UTC
Originally reported by @merges at https://github.com/facebook/react/issues/1529

-----

0. Visit http://facebook.github.io/react/html-jsx.html
1. Paste `<div className="blah"></div>` into Live JSX Editor
2. Observe conversion

EXPECTED RESULT
className is still className in the conversion

ACTUAL RESULT
className is converted to classname; this is invalid JSX

**Comment by jhiswin** [comment] 2015-05-10 12:59
Is actually a dupe of #8 , which is now fixed.

**Closed** 2015-05-10 19:52 UTC
